server:
  port: 9401

spring:
  profiles:
    active: dev

  application:
    name: security-oauth2-auth

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.22:8848
        username: nacos
        password: nacos

  redis:
    host: 192.168.123.22
    port: 6379
    password: Hacfin_Redis8
    timeout: 6000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 10
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: 10000ms
        # 最大空闲
        max-idle: 10
        # 最小空闲
        min-idle: 0
      #cluster:       # 集群配置
      #nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
      #max-redirects: 2  # 最大重定向次数

management:
  endpoints:
    web:
      exposure:
        include: "*"
