server:
  port: 19002


spring:
  application:
    name: admin-client
  #boot:
  #  admin:
  #    client:
  #      #配置admin-server地址
  #      url: http://localhost:19001

  cloud:
  #Nacos
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.123.22:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


#添加开启admin的日志监控
logging:
  file:
    name: logs/admin-client.log