server:
  port: 19011

spring:
  application:
    name: admin-security-server

  cloud:
    #Nacos
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.123.22:8848

  # 配置登录用户名和密码
  security:
    user:
      name: admin
      password: 123456


  # 配置admin
  boot:
    admin:
      ui:
        #页头
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>服务监控</span>
        #登录的标题
        title: 服务监控
        #隐藏 about 菜单
        view-settings:
          - name: about
            enabled: false
      discovery:
        #不显示admin-server的监控信息
        ignored-services: ${spring.application.name}
