server:
  port: 28081

spring:
  application:
    name: rocketmq-produce

  cloud:
    stream:
      # Spring Cloud Stream 配置项，对应 BindingProperties Map
      bindings:
        output-common:
          #RocketMQ Topic
          destination: topic-common-01
          content-type: application/json
        output-tx:
          destination: topic-tx-01
          content-type: application/json

      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: 192.168.123.22:9876

        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          output-common:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              #生产者分组
              group: group-common
              #同步发送消息
              sync: true
              #最大字节数
              maxMessageSize: 8249344
              #超时时间
              sendMessageTimeout: 3000
          tx-output:
            producer:
              #group name
              group: group-tx
              #发送事务消息
              transactional: true

logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'