server:
  port: 28081
spring:
  application:
    name: rocketmq-produce-example
  cloud:
    stream:
      bindings:
        output1:
          content-type: application/json
          destination: test-topic
        output2:
          content-type: application/json
          destination: TransactionTopic
        output3:
          content-type: text/plain
          destination: pull-topic

      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output1:
            producer:
              group: binder-group
              sync: true
          output2:
            producer:
              group: myTxProducerGroup
              transactional: true
          output3:
            producer:
              group: pull-binder-group

logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'