langyastudio:
  task:
    fixedDelaySchedule: 60000
  disk:
    local:
      root: /mnt/volume/edu/pms/
      #只有在windows运行时才生效
      #use for test on windows OS
      win-root: Z:/volume/edu/pms/
      #文件存储路径
      root-file: ${langyastudio.disk.local.root}file/
      #转码路径自动映射为mts/
      root-mts: ${langyastudio.disk.local.root}mts/
      #文件存储临时路径
      root-tmp: ${langyastudio.disk.local.root}temp/upload/
      #-图片-可直接浏览的文件大小10M
      browse-img-max-size: 10485760
      #-图片-可转码的文件大小20M
      cvt-img-max-size: 20971520
      # 最大文件大小，默认10M
      max-size: 10485760
      # 是否允许空文件:
      allow-empty: false
      # 允许的文件类型:
      allow-types: jpg, png, gif

server:
  # 服务端口
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://192.168.123.22:3306/edu_account
    username: root
    password: Hacfin_Mysql8
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 1
      max-wait: 6000
      #pool-prepared-statements:
      #max-pool-prepared-statement-per-connection-size:
      validation-query: SELECT 1
      #validation-query-timeout:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #max-evictable-idle-time-millis:
      filters: wall

  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        #关闭应用程序时，是否等待任务执行完毕
        await-termination: true
        await-termination-period: 60000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    classpath*:mapper/*.xml

  configuration:
    auto-mapping-behavior: partial
    # 开启驼峰命名
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      # 表名前缀
      table-prefix:

  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

#actuator
info:
  name: spring boot app
  version: 1.0.1
  maintainer: langyastudio
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #health, info
        include: health, info, beans, env, conditions, httptrace, configprops, threaddump, loggers, mappings, metrics

      #修改访问地址
      #base-path: /monitor
      #path-mapping:
      #  health: check-health
