langyastudio:
  disk:
    local:
      root: /mnt/volume/edu/pms/
      #只有在windows运行时才生效
      #use for test on windows OS
      win-root: Z:/volume/edu/pms/
      #文件存储路径
      root-file: ${langyastudio.disk.local.root}file/
      #转码路径自动映射为mts/
      root-mts: ${langyastudio.disk.local.root}mts/
      #文件存储临时路径
      root-tmp: ${langyastudio.disk.local.root}temp/upload/
      #-图片-可直接浏览的文件大小10M
      browse-img-max-size: 10485760
      #-图片-可转码的文件大小20M
      cvt-img-max-size: 20971520
      # 最大文件大小，默认10M
      max-size: 10485760
      # 是否允许空文件:
      allow-empty: false
      # 允许的文件类型:
      allow-types: jpg, png, gif

server:
  # 服务端口
  port: ${APP_PORT:8888}