server:
  port: 18082

spring:
  application:
    name: service-provider

  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        #Nacos
        server-addr: 192.168.123.22:8848
        cluster-name: service-provider

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'