version: '3.5'

services:
  nacos-registry:
    image: nacos/nacos-server:2.0.3
    container_name: nacos-registry
    #command:
    restart: always
    #https://nacos.io/zh-cn/docs/quick-start-docker.html
    environment:
      - "MODE=standalone"
    networks:
      edu-net:
        ipv4_address: 172.28.0.40
    ports:
      - 8848:8848


  sentinel-dashboard:
    image: bladex/sentinel-dashboard:1.8.0
    container_name: sentinel-dashboard
    #account and password: [sentinel sentinel]
    #修改默认密码为 123456
    #https://sentinelguard.io/zh-cn/docs/dashboard.html
    environment:
      - sentinel.dashboard.auth.password=123456
    restart: always
    networks:
      edu-net:
        ipv4_address: 172.28.0.50
    ports:
      - 8858:8858


  mongo:
    image: mongo:4.4.11
    container_name: mongo
    command: [ "--bind_ip_all" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    restart: always
    networks:
      edu-net:
        ipv4_address: 172.28.0.60
    volumes:
      - /mnt/volume/mongo/data:/data/db
      - /mnt/volume/mongo/log:/var/log/mongodb
    ports:
      - 27017:27017


  # http://seata.io/zh-cn/docs/ops/deploy-by-docker-compose.html
  seata:
    image: seataio/seata-server:1.4.2
    container_name: seata
    ports:
      - "8091:8091"
    environment:
      # 指定seata服务启动端口
      - SEATA_PORT=8091
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务
      - SEATA_IP=192.168.123.22
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      # 因为registry.conf中是nacos配置中心，只需要把registry.conf放到/mnt/volume/seata/config文件夹中
      - /mnt/volume/seata/conf:/root/seata-config
      - /mnt/volume/seata/logs:/root/logs
    restart: always


#docker network ls
#The actual name is volume_edu-net
#表示新建了 `172.28.0.0/16` 的网络，名称为 edu-net
#新建网络是为了实现同主机的多个容器间网络互通，走内网，类似于软件交换机
networks:
  edu-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16