// automatically generated by the FlatBuffers compiler, do not modify

package com.langyastudio.serialization.flatbuffer.monster;

@SuppressWarnings("unused")
public final class Equipment {
  private Equipment() { }
  public static final byte NONE = 0;
  public static final byte Weapon = 1;

  public static final String[] names = { "NONE", "Weapon", };

  public static String name(int e) { return names[e]; }
}

