server:
  port: 18091


spring:
  application:
    name: nacos-discovery-consumer

  cloud:
    #Nacos
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.123.22:8848
        namespace: public
        cluster-name: DEFAULT
        group: DEFAULT_GROUP


service-url:
  nacos-discovery-provider: nacos-discovery-provider


#feign log
logging:
  level:
    com.langyastudio.cloud.service.EchoService: debug


#feign client config
#https://cloud.spring.io/spring-cloud-openfeign/reference/html/appendix.html
feign:
  okhttp:
    enabled: true
  httpclient:
    connectionTimeout: 10000
    okhttp:
      readTimeout: 10000
  compression:
    request:
      #是否对请求进行GZIP压缩
      enabled: true
      #指定压缩的请求数据类型
      mime-types: text/xml,application/xml,application/json
      #超过该大小的请求会被压缩
      min-request-size: 1024
    response:
      #是否对响应进行GZIP压缩
      enabled: true

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'