server:
  port: 18091

spring:
  application:
    name: nacos-discovery-consumer

  cloud:
    #Nacos
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.123.22:8848
        namespace: public
        cluster-name: DEFAULT
        group: DEFAULT_GROUP


service-url:
  nacos-discovery-provider: http://nacos-discovery-provider


management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'