server:
  # 服务端口
  port: ${APP_PORT:8080}
  # 错误页，指定发生错误时，跳转的URL
  error:
    path: /error
  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
  # address=192.168.0.6
  servlet:
    # spring 2.x 中文乱码
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev
  application:
    name: websocket
  #文件上传限制配置
  servlet:
    multipart:
      # 文件最大限制
      max-file-size: 1024MB
      # 请求最大限制
      max-request-size: 1024MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0