server:
  port: 20001


spring:
  application:
    name: sentinel-server

  main:
    allow-circular-references: true

  cloud:
    #Nacos
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.123.22:8848
        namespace: public
        cluster-name: DEFAULT
        group: DEFAULT_GROUP

    #sentinel
    sentinel:
      transport:
        #dashboard地址
        dashboard: 192.168.123.22:8858
        port: 8719
      #config datasource
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.123.22:8848
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-sentinel
            #namespace: public
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

feign:
  sentinel:
    #打开 sentinel 对 feign 的支持
    enabled: true

#feign log
logging:
  level:
    com.langyastudio.cloud.service.EchoService: debug

service-url:
  nacos-discovery-provider: http://nacos-discovery-provider


management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'